"""descripcion

Revision ID: 1267d4bfb04c
Revises: 4695d1c4d543
Create Date: 2026-05-23 23:00:17.799430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1267d4bfb04c'
down_revision: Union[str, Sequence[str], None] = '4695d1c4d543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('imagenes_radar', 'tiene_marco',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('metricas_procesamiento', 'error_relleno_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.drop_constraint(op.f('fk_metricas_procesamiento_imagen_id_imagenes_radar'), 'metricas_procesamiento', type_='foreignkey')
    op.alter_column('procesamiento_pasos', 'exitoso',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(op.f('fk_procesamiento_pasos_imagen_id_imagenes_radar'), 'procesamiento_pasos', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_procesamiento_pasos_imagen_id_imagenes_radar'), 'procesamiento_pasos', 'imagenes_radar', ['imagen_id'], ['id'], ondelete='SET NULL')
    op.alter_column('procesamiento_pasos', 'exitoso',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_foreign_key(op.f('fk_metricas_procesamiento_imagen_id_imagenes_radar'), 'metricas_procesamiento', 'imagenes_radar', ['imagen_id'], ['id'], ondelete='SET NULL')
    op.alter_column('metricas_procesamiento', 'error_relleno_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('imagenes_radar', 'tiene_marco',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
